server:
  port: 8001

spring:
  application:
    name: springcloud-eureka1

eureka:
  instance:
    # 域名
    hostname: eureka1
    appname: eureka
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka2:8002/eureka